/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class FrmTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form FrmTrangChu
     */
    public FrmTrangChu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        btnSignOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNhanVien = new javax.swing.JMenu();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuSanPham = new javax.swing.JMenu();
        mniKhoHang = new javax.swing.JMenuItem();
        mnuHoaDon = new javax.swing.JMenu();
        mniHoaDon = new javax.swing.JMenuItem();
        mnuTraCuu = new javax.swing.JMenu();
        mniTimKiem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAPTOP HOANGTIGER");

        Desktop.setBackground(new java.awt.Color(204, 204, 255));

        btnSignOut.setText("Đăng xuất");
        btnSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        Desktop.setLayer(btnSignOut, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignOut)
                .addContainerGap(972, Short.MAX_VALUE))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addComponent(btnSignOut)
                .addContainerGap())
        );

        mnuNhanVien.setText("NHÂN VIÊN");

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/staff.png"))); // NOI18N
        mniNhanVien.setText("Danh sách nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuNhanVien.add(mniNhanVien);

        jMenuBar1.add(mnuNhanVien);

        mnuSanPham.setText("SẢN PHẨM");

        mniKhoHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        mniKhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/warehouse.png"))); // NOI18N
        mniKhoHang.setText("Kho hàng");
        mniKhoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoHangActionPerformed(evt);
            }
        });
        mnuSanPham.add(mniKhoHang);

        jMenuBar1.add(mnuSanPham);

        mnuHoaDon.setText("HÓA ĐƠN");

        mniHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        mniHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bill.png"))); // NOI18N
        mniHoaDon.setText("Hóa đơn");
        mniHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHoaDonActionPerformed(evt);
            }
        });
        mnuHoaDon.add(mniHoaDon);

        jMenuBar1.add(mnuHoaDon);

        mnuTraCuu.setText("TRA CỨU");

        mniTimKiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mniTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        mniTimKiem.setText("Tìm kiếm sản phẩm");
        mniTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimKiemActionPerformed(evt);
            }
        });
        mnuTraCuu.add(mniTimKiem);

        jMenuBar1.add(mnuTraCuu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        // TODO add your handling code here:
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất!");
        if(cf == 0){
            FrmDangNhap FrmDN = new FrmDangNhap();
            FrmDN.show();
            this.dispose();
        }
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void mniTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimKiemActionPerformed
        // TODO add your handling code here:
        FrmTraCuu frm = new FrmTraCuu();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mniTimKiemActionPerformed

    private void mniKhoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoHangActionPerformed
        // TODO add your handling code here:
        FrmKhoHang frm = new FrmKhoHang();
        Desktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_mniKhoHangActionPerformed

    private void mniHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHoaDonActionPerformed
        try {
            // TODO add your handling code here:
            FrmHoaDon frm = new FrmHoaDon();
            Desktop.add(frm);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniHoaDonActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        try {
            // TODO add your handling code here:
            FrmNhanVien frm = new FrmNhanVien();
            Desktop.add(frm);
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmTrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniHoaDon;
    private javax.swing.JMenuItem mniKhoHang;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuItem mniTimKiem;
    private javax.swing.JMenu mnuHoaDon;
    private javax.swing.JMenu mnuNhanVien;
    private javax.swing.JMenu mnuSanPham;
    private javax.swing.JMenu mnuTraCuu;
    // End of variables declaration//GEN-END:variables
}
